package dnd.Model.Itens;

/**
 *
 * @author Murilo
 */
public enum EquipTipo {
    LIGHT_ARMOR, MEDIUM_ARMOR, HEAVY_ARMOR, SIMPLE_WEAPON, SIMPLE_WEAPON_2H,
    MARTIAL_WEAPON, MARTIAL_WEAPON_2H, SIMPLE_AMMO, SIMPLE_AMMO_2H, MARTIAL_AMMO,
    MARTIAL_AMMO_2H, SIMPLE_THROW, MARTIAL_THROW
}
