package dnd.Model;

/**
 *
 * @author Murilo
 */
public enum Pericia {
    ATLETISMO, ACROBACIA, FURTIVIDADE, PRESTIDIGITACAO, ARCANISMO, HISTORIA,
    INVESTIGACAO, NATUREZA, RELIGIAO, ADESTRAR, INTUICAO, MEDICINA, PERCEPCAO,
    SOBREVIVENCIA, ATUACAO, ENGANACAO, INTIMIDACAO, PERSUASSAO
}
