/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dnd.View;

import dnd.Controller.Controller;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Murilo
 */
public class JanelaAtaque extends javax.swing.JDialog {

    public DefaultComboBoxModel atacanteModel;
    public DefaultComboBoxModel alvoModel;
    /**
     * Creates new form janelaAtaque
     */
    public JanelaAtaque(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        radioAtacJog.setSelected(true);
        radioAlvoNPC.setSelected(true);
        radioComum.setSelected(true);
        comboAtacJog.setModel(Controller.getComboJogadores(0));
        comboAlvoJog.setModel(Controller.getComboJogadores(1));
        comboAtacNPC.setModel(Controller.getComboNPCs(0));
        comboAlvoNPC.setModel(Controller.getComboNPCs(1));
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        radioAtacJog = new javax.swing.JRadioButton();
        radioAtacNPC = new javax.swing.JRadioButton();
        comboAtacJog = new javax.swing.JComboBox<>();
        comboAtacNPC = new javax.swing.JComboBox<>();
        radioComum = new javax.swing.JRadioButton();
        radioVantagem = new javax.swing.JRadioButton();
        radioDesvantagem = new javax.swing.JRadioButton();
        botaoAtacar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        comboAlvoJog = new javax.swing.JComboBox<>();
        comboAlvoNPC = new javax.swing.JComboBox<>();
        radioAlvoNPC = new javax.swing.JRadioButton();
        radioAlvoJog = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ataque");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Atacante"));

        radioAtacJog.setText("Jogador");
        radioAtacJog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAtacJogActionPerformed(evt);
            }
        });

        radioAtacNPC.setText("NPC");
        radioAtacNPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAtacNPCActionPerformed(evt);
            }
        });

        comboAtacJog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboAtacNPC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboAtacJog, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboAtacNPC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioAtacJog)
                    .addComponent(radioAtacNPC))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAtacJog)
                    .addComponent(comboAtacJog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAtacNPC)
                    .addComponent(comboAtacNPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        radioComum.setText("Ataque Comum");
        radioComum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioComumActionPerformed(evt);
            }
        });

        radioVantagem.setText("Vantagem");
        radioVantagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVantagemActionPerformed(evt);
            }
        });

        radioDesvantagem.setText("Desvantagem");
        radioDesvantagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDesvantagemActionPerformed(evt);
            }
        });

        botaoAtacar.setText("Atacar");
        botaoAtacar.setToolTipText("");

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Alvo"));

        comboAlvoJog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboAlvoNPC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        radioAlvoNPC.setText("NPC");
        radioAlvoNPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAlvoNPCActionPerformed(evt);
            }
        });

        radioAlvoJog.setText("Jogador");
        radioAlvoJog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAlvoJogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboAlvoJog, 0, 135, Short.MAX_VALUE)
                    .addComponent(comboAlvoNPC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioAlvoJog)
                    .addComponent(radioAlvoNPC))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAlvoJog)
                    .addComponent(comboAlvoJog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAlvoNPC)
                    .addComponent(comboAlvoNPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 41, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(botaoAtacar)
                                .addGap(18, 18, 18)
                                .addComponent(botaoCancelar)
                                .addGap(41, 41, 41))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioDesvantagem)
                                    .addComponent(radioVantagem)
                                    .addComponent(radioComum))
                                .addGap(73, 73, 73))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioComum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioVantagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioDesvantagem)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAtacar)
                    .addComponent(botaoCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        super.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void radioAtacJogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAtacJogActionPerformed
        radioAtacJog.setSelected(true);
        radioAtacNPC.setSelected(false);
    }//GEN-LAST:event_radioAtacJogActionPerformed

    private void radioAlvoJogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAlvoJogActionPerformed
        radioAlvoJog.setSelected(true);
        radioAlvoNPC.setSelected(false);
    }//GEN-LAST:event_radioAlvoJogActionPerformed

    private void radioAtacNPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAtacNPCActionPerformed
        radioAtacJog.setSelected(false);
        radioAtacNPC.setSelected(true);
    }//GEN-LAST:event_radioAtacNPCActionPerformed

    private void radioAlvoNPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAlvoNPCActionPerformed
        radioAlvoJog.setSelected(false);
        radioAlvoNPC.setSelected(true);
    }//GEN-LAST:event_radioAlvoNPCActionPerformed

    private void radioComumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioComumActionPerformed
        radioComum.setSelected(true);
        radioVantagem.setSelected(false);
        radioDesvantagem.setSelected(false);
    }//GEN-LAST:event_radioComumActionPerformed

    private void radioVantagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVantagemActionPerformed
        radioComum.setSelected(false);
        radioVantagem.setSelected(true);
        radioDesvantagem.setSelected(false);
    }//GEN-LAST:event_radioVantagemActionPerformed

    private void radioDesvantagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDesvantagemActionPerformed
        radioComum.setSelected(false);
        radioVantagem.setSelected(false);
        radioDesvantagem.setSelected(true);
    }//GEN-LAST:event_radioDesvantagemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaAtaque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaAtaque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaAtaque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaAtaque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JanelaAtaque dialog = new JanelaAtaque(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAtacar;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JComboBox<String> comboAlvoJog;
    private javax.swing.JComboBox<String> comboAlvoNPC;
    private javax.swing.JComboBox<String> comboAtacJog;
    private javax.swing.JComboBox<String> comboAtacNPC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton radioAlvoJog;
    private javax.swing.JRadioButton radioAlvoNPC;
    private javax.swing.JRadioButton radioAtacJog;
    private javax.swing.JRadioButton radioAtacNPC;
    private javax.swing.JRadioButton radioComum;
    private javax.swing.JRadioButton radioDesvantagem;
    private javax.swing.JRadioButton radioVantagem;
    // End of variables declaration//GEN-END:variables
}
